import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./_components/nav-bar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ProtectedLayoutProps {
  children: React.ReactNode;
}

export default async function ProtectedLayout({ children }: ProtectedLayoutProps) {
  return (
    
      <div className={inter.variable}>
        <NavBar />
        <main className="p-5">{children}</main>
      </div>
    
  );
}
